apiVersion: v1
kind: Service
metadata:
  name: login-flask-service
spec:
  selector:
    app: login-flask-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-flask-app
spec:
  selector:
    matchLabels:
      app: login-flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: login-flask-app
    spec:
      containers:
        - name: login-flask-app
          image: himanshudas75/login-flask-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: login-flask-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: login-flask-config
data:
  MONGO_URI: "mongodb+srv://mis-admin:mis_2023@login-flask-db-svc.default.svc.cluster.local/mis?ssl=false&authSource=admin"
  JWT_SECRET_KEY: "very_secret_key"
  JWT_IDENTITY_CLAIM: "identity"
  JWT_ACCESS_TOKEN_EXPIRES: "600"
